// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCM9A3bDZ7hzsE-_kNcg_yU8f3tGeEqog',
    appId: '1:363255228212:web:3d158d742b40ab0584a761',
    messagingSenderId: '363255228212',
    projectId: 'bruroam',
    authDomain: 'bruroam.firebaseapp.com',
    storageBucket: 'bruroam.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACyqcxFmAx5pPo22GkfRVNCMbrcDAungc',
    appId: '1:363255228212:android:cb71e5391f3d8f3484a761',
    messagingSenderId: '363255228212',
    projectId: 'bruroam',
    storageBucket: 'bruroam.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSizIw5GWB1-cs1pvmCOY6gULMv5b9yNw',
    appId: '1:363255228212:ios:e6225f48a0e9100f84a761',
    messagingSenderId: '363255228212',
    projectId: 'bruroam',
    storageBucket: 'bruroam.firebasestorage.app',
    iosBundleId: 'com.app.bruroam',
  );
}
